-- MERGE 
-- CRIAR TABELA TESTE E INSERIR ALGUNS DADOS

CREATE TABLE DEPT (
    DEPTNO  NUMBER(2),
    DNAME   VARCHAR2(14),
    LOC     VARCHAR2(13));
  
CREATE TABLE DEPT_ONLINE AS (SELECT * FROM DEPT WHERE ROWNUM=0);
    
INSERT INTO DEPT VALUES
(40,'OPERATIONS','BOSTON');

COMMIT;
 
SELECT * FROM DEPT_ONLINE;

-- FAZER MERGE
MERGE INTO DEPT D 
        USING (SELECT DEPTNO,DNAME,LOC
               FROM DEPT_ONLINE) O 
        ON (D.DEPTNO = O.DEPTNO)
        WHEN MATCHED THEN
             UPDATE SET D.DNAME = O.DNAME, D.LOC = O.LOC
        WHEN NOT MATCHED THEN
             INSERT (D.DEPTNO, D.DNAME,D.LOC)
             VALUES (O.DEPTNO, O.DNAME,O.LOC);
             
SELECT * FROM DEPT;

SELECT * FROM DEPT_ONLINE;

