-- NOCOPY
--- UTILIZAR AO COLOCAR UM PARÂMETRO DE SAÍDA EM UMA PROCEDURE

--JOB
-- TABELA TESTE
CREATE TABLE TESTE (COD NUMBER);

-- SEQUENCE TESTE
CREATE SEQUENCE SEQ_TESTE
START WITH 1
INCREMENT BY 1;

-- CRIAR O JOB
DECLARE 

X NUMBER;

BEGIN 
 SYS.DBMS_JOB.SUBMIT
 ( JOB => X
 , WHAT => '
 
BEGIN 
INSERT INTO TESTE VALUES (SEQ_TESTE.NEXTVAL);
COMMIT;
END;'
, NEXT_DATE => TO_DATE('13/07/2021 16:24:00','DD/MM/YYYY HH24:MI:SS')
,INTERVAL => 'SYSDATE+2/1440'
,NO_PARSE => FALSE
);

SYS.dbms_output.put_line('JOB NUMBER IS: '|| TO_CHAR(X));

COMMIT;
END;


-- ALTERAÇÕE E TESTES

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY HH24:MI:SS';

SELECT SYSDATE+2/1440 FROM DUAL;

SELECT 60*24 FROM DUAL;

SELECT COD FROM TESTE;