-- RAISE APLICATION ERROR
DECLARE 
SEM_COMISSAO EXCEPTION;
COMISSAO NUMBER;

BEGIN
IF COMISSAO IS NULL THEN
RAISE SEM_COMISSAO;
END IF;

EXCEPTION WHEN SEM_COMISSAO THEN
RAISE_APPLICATION_ERROR(-20000, 'Não há comissão!');

END;