-- VIEW
CREATE VIEW V_DPTO AS SELECT *
FROM departments WITH READ ONLY;

SELECT
    *
FROM V_DPTO;

DROP VIEW V_DPTO;

INSERT INTO V_DPTO VALUES (490,'A',NULL,NULL);


-- VIEW MATERIALIZED
CREATE MATERIALIZED VIEW LOG ON DEPARTMENTS;


CREATE MATERIALIZED VIEW MV_DPTO AS 
SELECT * FROM DEPARTMENTS;

SELECT COUNT(*) FROM DEPARTMENTS;

SELECT COUNT(*) FROM MV_DPTO;

delete from DEPARTMENTS
where department_id = 500;

EXEC DBMS_MVIEW.REFRESH('MV_DPTO','C');


-- INDEX

CREATE TABLE TB_DEPTO AS SELECT * FROM DEPARTMENTS;

SELECT * FROM TB_DEPTO
WHERE department_id=10;

CREATE INDEX IDX_DEPARTMENT_ID ON TB_DEPTO (DEPARTMENT_ID);


-- SYNONYMS
CREATE SYNONYM SYN_EMP FOR EMPLOYEES;

SELECT
    *
FROM syn_emp;

